table _Measures
	lineageTag: 8876c241-1dc5-4929-9e8c-bbfa0cf72d8a

	measure 'Total Actuals' =
			CALCULATE(
			    SUM(fact_finances[amount]),
			    fact_finances[Scenario] = "Actual"
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 489ef06f-12bd-48e0-bbdc-c66a50682ba1

	measure 'Total Budget' =
			CALCULATE(
			    SUM(fact_finances[amount]),
			    fact_finances[Scenario] = "Budget"
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: e8de82ab-8c9e-4df7-8c38-84224c30ff7d

	measure 'Variance ($)' = [Total Actuals] - [Total Budget]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: f20d5c41-8f5f-4a3f-84d4-28b301431fcc

	measure 'Variance (%)' = DIVIDE([Variance ($)], [Total Budget], 0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: ad0b0373-c6cd-4860-9dc4-83b3e34bcf1b

	measure 'YTD Actuals' = TOTALYTD([Total Actuals], dim_date[Date])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 18cd5099-5561-4560-848f-30de9a842f1b

	measure 'YTD Budget' = TOTALYTD([Total Budget], dim_date[Date])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: fa9c7755-dff5-4b36-a3ee-662551cf16b4

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

